import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import React from "react";

interface CourseSelectorProps {
    onUrlImport: (url: string) => void;
}
 
export function ImportModules({ onUrlImport }: CourseSelectorProps) {

    const [url, setUrl] = React.useState("")

    const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        setUrl(event.target.value);
      };
    
      const handleImportClick = () => {
        onUrlImport(url);
      };


  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Import Modules</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Import Modules</DialogTitle>
          <DialogDescription>
            Paste the url generated by clicking on the Share/Sync button.
            This will overwrite your existing modules.
          </DialogDescription>
        </DialogHeader>
          <div className="grid grid-cols-4 mb-5">
            <Input
              id="username"
              className="col-span-4"
              value={url}
              onChange={handleInputChange}
            />
          </div>
        <DialogFooter>
          <Button type="submit" onClick={handleImportClick}>Import</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}